DROP TABLE IF EXISTS author;
CREATE TABLE author(id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(255));
DROP TABLE IF EXISTS genre;
CREATE TABLE genre(id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(255));
DROP TABLE IF EXISTS book;
CREATE TABLE book(
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    authorId BIGINT,
    genreId BIGINT,
    CONSTRAINT fkBookAuthor FOREIGN KEY (authorId) REFERENCES author(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fkBookGenre FOREIGN KEY (genreId) REFERENCES genre(id) ON UPDATE RESTRICT ON DELETE RESTRICT);
