version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - nw
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    hostname: kafka
    container_name: kafka
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - nw
  author:
    build:
      context: homework-17-author
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8081:8081"
    networks:
      - nw
  library:
    build:
      context: homework-17-library
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - AUTHOR_SERVICE_HOST=author
      - AUTHOR_SERVICE_PORT=8081
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - author
      - kafka
    networks:
      - nw
  genre:
    build:
      context: homework-17-genre
      dockerfile: Dockerfile
    privileged: true
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - kafka
    networks:
      - nw
networks:
  nw:
