DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS role;
CREATE TABLE author(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE user(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255),
    password VARCHAR(255));
CREATE TABLE role(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255));
CREATE TABLE user_role(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    role_id BIGINT,
    CONSTRAINT fkUserRoleUser FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fkUserRoleRole FOREIGN KEY (role_id) REFERENCES role(id) ON UPDATE CASCADE ON DELETE RESTRICT);